### ISSUE TITLE
Merge closing result in detection of spurious cycles

### ISSUE THREAD

**Issue by MinhChauNGUYEN** [alexis-michaud/egg#10]
Here is a case where the speaker's voice is hoarse (he clears his throat immediately afterwards)

![AExtremlyLongCycle_M14_3502_EGG](https://user-images.githubusercontent.com/37310321/59688478-0f7b0b00-91de-11e9-9d6b-c82151077388.png)
![AExtremlyLongCycle_M14_3502_DEGG](https://user-images.githubusercontent.com/37310321/59688481-11dd6500-91de-11e9-9380-56e5d055672d.png)
In this case, `PeakDet` detected erroneously a spurious cycle. In fact, the 16th cycle is a part of an extremly long glottal cycle with triple closing peaks, which last from 16th cycle to 17th cycle. 
As a result, it leads to an unreasonale curve of f0 values with two spurious values. 
![AExtremlyLongCycle_M14_3502_F0 Oq](https://user-images.githubusercontent.com/37310321/59689503-10ad3780-91e0-11e9-8591-f43009bac788.png)
In order to deal with cases like this, `Peakdet` should implement a solution to merge spurious cycles.

Source: Muong data, speaker M14, token 3501, syllable /kiɛŋ4/ 'wing'
Audio file: https://www.dropbox.com/s/eo7lawj9c8be160/AExtremlyLongCycle_M14_3502_Audio.wav?dl=0

**Comment by MinhChauNGUYEN** [comment]
The script works. You can close the issue. 

Thanks.
Minh Châu.

**Comment by alexis-michaud** [comment]
👍 
Thanks for the testing. I'll bump the version number.
