### ISSUE TITLE
Display result again after removing one cycle 

### ISSUE THREAD

**Issue by MinhChauNGUYEN** [alexis-michaud/egg#2]
> To suppress first period, enter 1. To suppress last period, enter 9

After removing last periods, it would be good to display the values again on the figure.

**Comment by alexis-michaud** [comment]
Done. Some cleanup of figure display has been done. 

After re-syncing with `origin`, check that the new function `plotfig1.m` has appeared in your local copy of the `peakdet_inter` folder. Then run `peakdet_inter` as usual.

(Issue #1 is likely to take more time, as it relates to the key task of analyzing shapes in the EGG signal.)

Thanks for the beta-testing! 👍
