### ISSUE TITLE
Warning and automatically resume for step of Oq suppression 

### ISSUE THREAD

**Issue by MinhChauNGUYEN** [alexis-michaud/egg#4]
After suppressing some final cycles which normally don't possess precise opening peaks, because it is not displayed in figures of EGG and DEGG signal (only in figure of f0 and Oq), I often forget and try to exclude those cycles's Oq values. As a result, it crashes and stops the loop. Therefore, a warning and automatically resume for this step would be better for user.

**Comment by alexis-michaud** [comment]
Done: 
* there is now a safeguard against out-of-range values
* when an initial or final cycle is excluded by the user, then that cycle's number is de-assigned: the signals are plotted anew with the new numbers.
Thus, using the first example in the gallery, here is the electroglottographic signal after leaving aside some cycles at beginning and end:
![image](https://user-images.githubusercontent.com/6072524/52919080-bfa73880-32fe-11e9-8d7b-96f19ea0daf2.png)
and its derivative:
![image](https://user-images.githubusercontent.com/6072524/52919098-eb2a2300-32fe-11e9-8919-d24f662880ef.png)

Let me know if this solves the issue.

**Comment by MinhChauNGUYEN** [comment]
Thank you so much. It works well.
